[ERROR] 2017-05-25 23:36:36,364 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 27, in render
    data = render_page('404')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 35, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 44, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 18, in resolve_route
    context = get_page_context_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 71, in get_page_context_from_template
    return get_page_info(option, app, app_path=app_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 203, in get_page_info
    setup_source(page_info)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 214, in setup_source
    jenv = frappe.get_jenv()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 14, in get_jenv
    set_filters(jenv)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 179, in set_filters
    for jenv_filter in (frappe.get_hooks(app_name=app).jenv_filter or []):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 798, in get_hooks
    hooks = _dict(load_app_hooks(app_name))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/newapp/newapp/hooks.py", line 86
    "Payment Entry": {
                  ^
SyntaxError: invalid syntax
[ERROR] 2017-05-25 23:38:01,188 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 65, in render
    data = render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 35, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 44, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 18, in resolve_route
    context = get_page_context_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 71, in get_page_context_from_template
    return get_page_info(option, app, app_path=app_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 203, in get_page_info
    setup_source(page_info)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 214, in setup_source
    jenv = frappe.get_jenv()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 14, in get_jenv
    set_filters(jenv)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 179, in set_filters
    for jenv_filter in (frappe.get_hooks(app_name=app).jenv_filter or []):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 798, in get_hooks
    hooks = _dict(load_app_hooks(app_name))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/newapp/newapp/hooks.py", line 86
    "Payment Entry": {
                  ^
SyntaxError: invalid syntax
[ERROR] 2017-05-25 23:38:03,466 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 65, in render
    data = render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 35, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 44, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 18, in resolve_route
    context = get_page_context_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 71, in get_page_context_from_template
    return get_page_info(option, app, app_path=app_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 203, in get_page_info
    setup_source(page_info)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 214, in setup_source
    jenv = frappe.get_jenv()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 14, in get_jenv
    set_filters(jenv)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 179, in set_filters
    for jenv_filter in (frappe.get_hooks(app_name=app).jenv_filter or []):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 798, in get_hooks
    hooks = _dict(load_app_hooks(app_name))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/newapp/newapp/hooks.py", line 86
    "Payment Entry": {
                  ^
SyntaxError: invalid syntax
[ERROR] 2017-05-25 23:39:05,718 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.async.get_user_info", 
 "data": "", 
 "sid": "440fa05e62c6193f7f1c334119968ec1a27eea69b7db6b208343ed1c"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 35, in execute_cmd
    for hook in frappe.get_hooks("override_whitelisted_methods", {}).get(cmd, []):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 800, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 70, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/newapp/newapp/hooks.py", line 86
    "Payment Entry": {
                  ^
SyntaxError: invalid syntax
[ERROR] 2017-05-25 23:39:05,774 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 23:39:05.718853-45.114.141.112-84c
[ERROR] 2017-05-25 23:39:19,430 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 22, in render
    path = resolve_path(path or frappe.local.request.path.strip('/ '))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 161, in resolve_path
    path = get_home_page()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 70, in get_home_page
    return frappe.cache().hget("home_page", frappe.session.user, _get_home_page)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 171, in hget
    value = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 46, in _get_home_page
    get_website_user_home_page = frappe.get_hooks('get_website_user_home_page')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 800, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 70, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/newapp/newapp/hooks.py", line 86
    "Payment Entry": {
                  ^
SyntaxError: invalid syntax
[ERROR] 2017-05-25 23:39:19,434 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 23:39:19.431016-47.30.78.112-573
[ERROR] 2017-05-25 23:39:21,804 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 22, in render
    path = resolve_path(path or frappe.local.request.path.strip('/ '))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 161, in resolve_path
    path = get_home_page()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 70, in get_home_page
    return frappe.cache().hget("home_page", frappe.session.user, _get_home_page)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 171, in hget
    value = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 46, in _get_home_page
    get_website_user_home_page = frappe.get_hooks('get_website_user_home_page')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 800, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 70, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/newapp/newapp/hooks.py", line 86
    "Payment Entry": {
                  ^
SyntaxError: invalid syntax
[ERROR] 2017-05-25 23:39:21,808 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 23:39:21.804409-47.30.78.112-b62
[ERROR] 2017-05-25 23:39:23,680 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 22, in render
    path = resolve_path(path or frappe.local.request.path.strip('/ '))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 161, in resolve_path
    path = get_home_page()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 70, in get_home_page
    return frappe.cache().hget("home_page", frappe.session.user, _get_home_page)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 171, in hget
    value = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 46, in _get_home_page
    get_website_user_home_page = frappe.get_hooks('get_website_user_home_page')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 800, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 70, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/newapp/newapp/hooks.py", line 86
    "Payment Entry": {
                  ^
SyntaxError: invalid syntax
[ERROR] 2017-05-25 23:39:23,683 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 23:39:23.680427-47.30.78.112-34e
[ERROR] 2017-05-25 23:39:25,728 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 22, in render
    path = resolve_path(path or frappe.local.request.path.strip('/ '))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 161, in resolve_path
    path = get_home_page()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 70, in get_home_page
    return frappe.cache().hget("home_page", frappe.session.user, _get_home_page)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 171, in hget
    value = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 46, in _get_home_page
    get_website_user_home_page = frappe.get_hooks('get_website_user_home_page')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 800, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 70, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/newapp/newapp/hooks.py", line 86
    "Payment Entry": {
                  ^
SyntaxError: invalid syntax
[ERROR] 2017-05-25 23:39:25,732 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 23:39:25.729268-47.30.78.112-c69
[ERROR] 2017-05-25 23:39:27,121 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 22, in render
    path = resolve_path(path or frappe.local.request.path.strip('/ '))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 161, in resolve_path
    path = get_home_page()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 70, in get_home_page
    return frappe.cache().hget("home_page", frappe.session.user, _get_home_page)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 171, in hget
    value = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 46, in _get_home_page
    get_website_user_home_page = frappe.get_hooks('get_website_user_home_page')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 800, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 70, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/newapp/newapp/hooks.py", line 86
    "Payment Entry": {
                  ^
SyntaxError: invalid syntax
[ERROR] 2017-05-25 23:39:27,126 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 23:39:27.121470-47.30.78.112-a61
[ERROR] 2017-05-25 23:40:09,611 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.async.get_user_info", 
 "data": "", 
 "sid": "440fa05e62c6193f7f1c334119968ec1a27eea69b7db6b208343ed1c"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 35, in execute_cmd
    for hook in frappe.get_hooks("override_whitelisted_methods", {}).get(cmd, []):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 800, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 70, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/newapp/newapp/hooks.py", line 86
    "Payment Entry": {
                  ^
SyntaxError: invalid syntax
[ERROR] 2017-05-25 23:40:09,964 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 23:40:09.612053-45.114.141.112-77d
[ERROR] 2017-05-25 23:40:24,062 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 22, in render
    path = resolve_path(path or frappe.local.request.path.strip('/ '))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 161, in resolve_path
    path = get_home_page()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 70, in get_home_page
    return frappe.cache().hget("home_page", frappe.session.user, _get_home_page)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 171, in hget
    value = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 46, in _get_home_page
    get_website_user_home_page = frappe.get_hooks('get_website_user_home_page')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 800, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 70, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/newapp/newapp/hooks.py", line 86
    "Payment Entry": {
                  ^
SyntaxError: invalid syntax
[ERROR] 2017-05-25 23:40:24,067 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 23:40:24.062790-47.30.78.112-f35
[ERROR] 2017-05-25 23:40:25,730 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 22, in render
    path = resolve_path(path or frappe.local.request.path.strip('/ '))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 161, in resolve_path
    path = get_home_page()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 70, in get_home_page
    return frappe.cache().hget("home_page", frappe.session.user, _get_home_page)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 171, in hget
    value = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 46, in _get_home_page
    get_website_user_home_page = frappe.get_hooks('get_website_user_home_page')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 800, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 70, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/newapp/newapp/hooks.py", line 86
    "Payment Entry": {
                  ^
SyntaxError: invalid syntax
[ERROR] 2017-05-25 23:40:25,734 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 23:40:25.730692-47.30.78.112-986
[ERROR] 2017-05-25 23:42:18,807 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.async.get_user_info", 
 "data": "", 
 "sid": "440fa05e62c6193f7f1c334119968ec1a27eea69b7db6b208343ed1c"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 35, in execute_cmd
    for hook in frappe.get_hooks("override_whitelisted_methods", {}).get(cmd, []):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 800, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 70, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/newapp/newapp/hooks.py", line 86
    "Payment Entry": {
                  ^
SyntaxError: invalid syntax
[ERROR] 2017-05-25 23:42:18,852 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 23:42:18.808607-45.114.141.112-50a
[ERROR] 2017-05-25 23:42:30,321 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 22, in render
    path = resolve_path(path or frappe.local.request.path.strip('/ '))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 161, in resolve_path
    path = get_home_page()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 70, in get_home_page
    return frappe.cache().hget("home_page", frappe.session.user, _get_home_page)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 171, in hget
    value = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 46, in _get_home_page
    get_website_user_home_page = frappe.get_hooks('get_website_user_home_page')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 800, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 70, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/newapp/newapp/hooks.py", line 86
    "Payment Entry": {
                  ^
SyntaxError: invalid syntax
[ERROR] 2017-05-25 23:42:30,327 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 23:42:30.322385-47.30.78.112-1ea
[ERROR] 2017-05-25 23:42:32,938 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 22, in render
    path = resolve_path(path or frappe.local.request.path.strip('/ '))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 161, in resolve_path
    path = get_home_page()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 70, in get_home_page
    return frappe.cache().hget("home_page", frappe.session.user, _get_home_page)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 171, in hget
    value = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 46, in _get_home_page
    get_website_user_home_page = frappe.get_hooks('get_website_user_home_page')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 800, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 70, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/newapp/newapp/hooks.py", line 86
    "Payment Entry": {
                  ^
SyntaxError: invalid syntax
[ERROR] 2017-05-25 23:42:32,993 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 23:42:32.939411-47.30.78.112-ef9
[ERROR] 2017-05-27 11:13:16,586 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.client.get_value", 
 "doctype": "Bank Master", 
 "filters": "{\"micr\":\"272011251\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
TypeError: get_value() takes at least 2 arguments (2 given)
[ERROR] 2017-05-27 11:13:16,645 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-27 11:13:16.587094-122.160.159.227-da6
[ERROR] 2017-05-27 15:10:21,176 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.client.get_value", 
 "doctype": "Bank Master", 
 "filters": "{\"micr\":\"751011021\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
TypeError: get_value() takes at least 2 arguments (2 given)
[ERROR] 2017-05-27 15:10:21,239 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-27 15:10:21.177304-122.160.159.227-1b8
[ERROR] 2017-05-27 15:15:06,060 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.client.get_value", 
 "doctype": "Bank Master", 
 "filters": "{\"micr\":\"507011009\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
TypeError: get_value() takes at least 2 arguments (2 given)
[ERROR] 2017-05-27 15:15:06,063 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-27 15:15:06.061168-122.160.159.227-025
[ERROR] 2017-05-27 15:16:53,222 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.client.get_value", 
 "doctype": "Bank Master", 
 "filters": "{\"micr\":\"312011002\"}"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
TypeError: get_value() takes at least 2 arguments (2 given)
[ERROR] 2017-05-27 15:16:53,278 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-27 15:16:53.223025-122.160.159.227-c67
[ERROR] 2017-05-28 09:37:04,224 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.query_report.export_query", 
 "file_format_type": "Excel", 
 "filters": "{\"from_date\":\"2017-04-01\",\"to_date\":\"2017-05-28\"}", 
 "report_name": "Stock Balance"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 157, in export_query
    result = [x for idx, x in enumerate(result) if idx == 0 or idx in visible_idx]
UnboundLocalError: local variable 'visible_idx' referenced before assignment
[ERROR] 2017-05-28 09:37:04,273 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-28 09:37:04.224611-47.30.187.121-0ae
[ERROR] 2017-05-28 09:38:48,684 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.query_report.export_query", 
 "file_format_type": "Excel", 
 "filters": "{\"company\":\"MyPaperKart Pvt Ltd\",\"from_date\":\"2017-04-28\",\"to_date\":\"2017-05-28\"}", 
 "report_name": "Stock Ledger"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 157, in export_query
    result = [x for idx, x in enumerate(result) if idx == 0 or idx in visible_idx]
UnboundLocalError: local variable 'visible_idx' referenced before assignment
[ERROR] 2017-05-28 09:38:48,690 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-28 09:38:48.685294-47.30.187.121-297
[ERROR] 2017-05-29 06:34:00,485 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "action": "Save", 
 "cmd": "frappe.desk.form.save.savedocs", 
 "doc": "{\"docstatus\":0,\"doctype\":\"Project\",\"name\":\"New Project 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Open\",\"project_type\":\"External\",\"is_active\":\"Yes\",\"percent_complete_method\":\"Task Completion\",\"priority\":\"Medium\",\"company\":\"MyPaperKart Pvt Ltd\",\"project_name\":\"Wedding Card  Industry\",\"expected_end_date\":\"2017-05-31\",\"notes\":\"\",\"expected_start_date\":\"2017-05-29\",\"customer\":\"\",\"users\":[{\"docstatus\":0,\"doctype\":\"Project User\",\"name\":\"New Project User 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"parent\":\"New Project 1\",\"parentfield\":\"users\",\"parenttype\":\"Project\",\"idx\":1,\"__unedited\":false,\"user\":\"Shobhit4Shobhit4800@gmail.com\"}],\"tasks\":[{\"docstatus\":0,\"doctype\":\"Project Task\",\"name\":\"New Project Task 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Open\",\"parent\":\"New Project 1\",\"parentfield\":\"tasks\",\"parenttype\":\"Project\",\"idx\":1,\"__unedited\":false,\"title\":\"wedding card\",\"start_date\":\"2017-05-29\",\"end_date\":\"2017-05-31\"}]}"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 230, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 253, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 192, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 771, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 666, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 891, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 874, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 660, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/projects/doctype/project/project.py", line 57, in validate
    self.send_welcome_email()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/projects/doctype/project/project.py", line 202, in send_welcome_email
    frappe.sendmail(user.user, subject=_("Project Collaboration Invitation"), content=content.format(*messages))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 418, in sendmail
    communication=communication, now=now, read_receipt=read_receipt, is_notification=is_notification)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/queue.py", line 61, in send
    email_account = get_outgoing_email_account(True, append_to=reference_doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/smtp.py", line 58, in get_outgoing_email_account
    frappe.OutgoingEmailError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 316, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 306, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 279, in _raise_exception
    raise raise_exception, encode(msg)
OutgoingEmailError: Please setup default Email Account from Setup > Email > Email Account
[ERROR] 2017-05-29 06:34:00,544 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-29 06:34:00.486354-47.30.187.121-76e
[ERROR] 2017-05-29 06:34:15,805 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "action": "Save", 
 "cmd": "frappe.desk.form.save.savedocs", 
 "doc": "{\"docstatus\":0,\"doctype\":\"Project\",\"name\":\"New Project 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Open\",\"project_type\":\"External\",\"is_active\":\"Yes\",\"percent_complete_method\":\"Task Completion\",\"priority\":\"Medium\",\"company\":\"MyPaperKart Pvt Ltd\",\"project_name\":\"Wedding Card  Industry\",\"expected_end_date\":\"2017-05-31\",\"notes\":\"\",\"expected_start_date\":\"2017-05-29\",\"customer\":\"\",\"users\":[{\"docstatus\":0,\"doctype\":\"Project User\",\"name\":\"New Project User 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"parent\":\"New Project 1\",\"parentfield\":\"users\",\"parenttype\":\"Project\",\"idx\":1,\"__unedited\":false,\"user\":\"Shobhit4Shobhit4800@gmail.com\"}],\"tasks\":[{\"docstatus\":0,\"doctype\":\"Project Task\",\"name\":\"New Project Task 1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"status\":\"Open\",\"parent\":\"New Project 1\",\"parentfield\":\"tasks\",\"parenttype\":\"Project\",\"idx\":1,\"__unedited\":false,\"title\":\"wedding card\",\"start_date\":\"2017-05-29\",\"end_date\":\"2017-05-31\"}]}"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 230, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 253, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 192, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 771, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 666, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 891, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 874, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 660, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/projects/doctype/project/project.py", line 57, in validate
    self.send_welcome_email()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/projects/doctype/project/project.py", line 202, in send_welcome_email
    frappe.sendmail(user.user, subject=_("Project Collaboration Invitation"), content=content.format(*messages))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 418, in sendmail
    communication=communication, now=now, read_receipt=read_receipt, is_notification=is_notification)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/queue.py", line 61, in send
    email_account = get_outgoing_email_account(True, append_to=reference_doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/smtp.py", line 58, in get_outgoing_email_account
    frappe.OutgoingEmailError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 316, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 306, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 279, in _raise_exception
    raise raise_exception, encode(msg)
OutgoingEmailError: Please setup default Email Account from Setup > Email > Email Account
[ERROR] 2017-05-29 06:34:15,823 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-29 06:34:15.806038-47.30.187.121-5ac
[ERROR] 2017-05-29 06:39:24,568 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "action": "Save", 
 "cmd": "frappe.desk.form.save.savedocs", 
 "doc": "{\"default_outgoing\":0,\"domain\":\"ymail.com\",\"email_id\":\"shobhacards@ymail.com\",\"__islocal\":1,\"doctype\":\"Email Account\",\"unreplied_for_mins\":30,\"use_imap\":1,\"owner\":\"Administrator\",\"use_ssl\":1,\"email_server\":\"imap.mail.yahoo.com\",\"always_use_account_email_id_as_sender\":0,\"email_sync_option\":\"UNSEEN\",\"default_incoming\":0,\"service\":\"GMail\",\"smtp_port\":\"587\",\"smtp_server\":\"smtp.mail.yahoo.com\",\"use_tls\":0,\"enable_incoming\":0,\"attachment_limit\":1,\"docstatus\":0,\"awaiting_password\":0,\"no_failed\":0,\"initial_sync_count\":\"250\",\"enable_auto_reply\":1,\"send_unsubscribe_message\":1,\"enable_outgoing\":1,\"uidnext\":0,\"add_signature\":1,\"password\":\"admin123\",\"email_account_name\":\"Rajeshwar Gupta\",\"name\":\"New Email Account 1\",\"idx\":0,\"footer\":\"Rajeshwar Gupta<div>Shobha Cards And Arts</div><div>3618/7 , Sudershan Market</div><div>Chawari Bazar ,Delhi 110006</div>\",\"login_id_is_different\":0,\"notify_if_unreplied\":0,\"__last_sync_on\":\"2017-05-29T01:09:06.814Z\",\"__unsaved\":1}"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 230, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 253, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 192, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 771, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 666, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 891, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 874, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 660, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 71, in validate
    self.check_smtp()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 137, in check_smtp
    server.sess
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/smtp.py", line 181, in sess
    (self.password or "").encode('utf-8'))
  File "/usr/lib/python2.7/smtplib.py", line 585, in login
    raise SMTPException("SMTP AUTH extension not supported by server.")
SMTPException: SMTP AUTH extension not supported by server.
[ERROR] 2017-05-29 06:39:24,584 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-29 06:39:24.569030-47.30.187.121-6c7
[ERROR] 2017-05-29 18:21:08,104 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.form.load.getdoc", 
 "doctype": "Payment Entry", 
 "name": "PE-00004"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 35, in getdoc
    if not doc.has_permission("read"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 155, in has_permission
    return frappe.has_permission(self.doctype, permtype, self, verbose=verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 500, in has_permission
    out = frappe.permissions.has_permission(doctype, ptype, doc=doc, verbose=verbose, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 93, in has_permission
    controller_perm = has_controller_permissions(doc, ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 302, in has_controller_permissions
    controller_permission = frappe.call(frappe.get_attr(method), doc=doc, ptype=ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.payment_entry_2
[ERROR] 2017-05-29 18:21:08,156 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-29 18:21:08.104711-122.160.159.227-005
[ERROR] 2017-05-29 18:21:48,381 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.form.load.getdoc", 
 "doctype": "Payment Entry", 
 "name": "PE-00004"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 35, in getdoc
    if not doc.has_permission("read"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 155, in has_permission
    return frappe.has_permission(self.doctype, permtype, self, verbose=verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 500, in has_permission
    out = frappe.permissions.has_permission(doctype, ptype, doc=doc, verbose=verbose, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 93, in has_permission
    controller_perm = has_controller_permissions(doc, ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 302, in has_controller_permissions
    controller_permission = frappe.call(frappe.get_attr(method), doc=doc, ptype=ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.payment_entry_2
[ERROR] 2017-05-29 18:21:48,386 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-29 18:21:48.382310-122.160.159.227-d9b
[ERROR] 2017-05-29 18:23:51,147 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.form.load.getdoc", 
 "doctype": "Payment Entry", 
 "name": "PE-00004"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 35, in getdoc
    if not doc.has_permission("read"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 155, in has_permission
    return frappe.has_permission(self.doctype, permtype, self, verbose=verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 500, in has_permission
    out = frappe.permissions.has_permission(doctype, ptype, doc=doc, verbose=verbose, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 93, in has_permission
    controller_perm = has_controller_permissions(doc, ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 302, in has_controller_permissions
    controller_permission = frappe.call(frappe.get_attr(method), doc=doc, ptype=ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.payment_entry_2
[ERROR] 2017-05-29 18:23:51,155 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-29 18:23:51.148562-122.160.159.227-0e6
[ERROR] 2017-05-29 18:27:27,463 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.form.load.getdoc", 
 "doctype": "Payment Entry", 
 "name": "PE-00004"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 35, in getdoc
    if not doc.has_permission("read"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 155, in has_permission
    return frappe.has_permission(self.doctype, permtype, self, verbose=verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 500, in has_permission
    out = frappe.permissions.has_permission(doctype, ptype, doc=doc, verbose=verbose, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 93, in has_permission
    controller_perm = has_controller_permissions(doc, ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 302, in has_controller_permissions
    controller_permission = frappe.call(frappe.get_attr(method), doc=doc, ptype=ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.payment_entry_2
[ERROR] 2017-05-29 18:27:27,471 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-29 18:27:27.464888-122.160.159.227-b6d
[ERROR] 2017-05-29 18:28:28,289 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.form.load.getdoc", 
 "doctype": "Payment Entry", 
 "name": "PE-00004"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 35, in getdoc
    if not doc.has_permission("read"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 155, in has_permission
    return frappe.has_permission(self.doctype, permtype, self, verbose=verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 500, in has_permission
    out = frappe.permissions.has_permission(doctype, ptype, doc=doc, verbose=verbose, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 93, in has_permission
    controller_perm = has_controller_permissions(doc, ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 302, in has_controller_permissions
    controller_permission = frappe.call(frappe.get_attr(method), doc=doc, ptype=ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.payment_entry_2
[ERROR] 2017-05-29 18:28:28,294 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-29 18:28:28.290322-122.160.159.227-5c9
[ERROR] 2017-05-29 18:32:17,914 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.form.load.getdoc", 
 "doctype": "Payment Entry", 
 "name": "PE-00004"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 35, in getdoc
    if not doc.has_permission("read"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 155, in has_permission
    return frappe.has_permission(self.doctype, permtype, self, verbose=verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 500, in has_permission
    out = frappe.permissions.has_permission(doctype, ptype, doc=doc, verbose=verbose, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 93, in has_permission
    controller_perm = has_controller_permissions(doc, ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 302, in has_controller_permissions
    controller_permission = frappe.call(frappe.get_attr(method), doc=doc, ptype=ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.payment_entry_2
[ERROR] 2017-05-29 18:32:17,923 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-29 18:32:17.916290-122.160.159.227-1da
[ERROR] 2017-05-29 18:33:06,955 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.form.load.getdoc", 
 "doctype": "Payment Entry", 
 "name": "PE-00001"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 35, in getdoc
    if not doc.has_permission("read"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 155, in has_permission
    return frappe.has_permission(self.doctype, permtype, self, verbose=verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 500, in has_permission
    out = frappe.permissions.has_permission(doctype, ptype, doc=doc, verbose=verbose, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 93, in has_permission
    controller_perm = has_controller_permissions(doc, ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 302, in has_controller_permissions
    controller_permission = frappe.call(frappe.get_attr(method), doc=doc, ptype=ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.payment_entry_2
[ERROR] 2017-05-29 18:33:06,960 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-29 18:33:06.955671-122.160.159.227-007
[ERROR] 2017-05-29 18:36:38,884 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.form.load.getdoc", 
 "doctype": "Payment Entry", 
 "name": "PE-00004"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 35, in getdoc
    if not doc.has_permission("read"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 155, in has_permission
    return frappe.has_permission(self.doctype, permtype, self, verbose=verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 500, in has_permission
    out = frappe.permissions.has_permission(doctype, ptype, doc=doc, verbose=verbose, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 93, in has_permission
    controller_perm = has_controller_permissions(doc, ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 302, in has_controller_permissions
    controller_permission = frappe.call(frappe.get_attr(method), doc=doc, ptype=ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.payment_entry_2
[ERROR] 2017-05-29 18:36:38,890 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-29 18:36:38.885063-122.160.159.227-e01
[ERROR] 2017-05-30 00:09:47,622 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.form.load.getdoc", 
 "doctype": "Payment Entry", 
 "name": "PE-00004"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 35, in getdoc
    if not doc.has_permission("read"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 155, in has_permission
    return frappe.has_permission(self.doctype, permtype, self, verbose=verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 500, in has_permission
    out = frappe.permissions.has_permission(doctype, ptype, doc=doc, verbose=verbose, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 93, in has_permission
    controller_perm = has_controller_permissions(doc, ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 302, in has_controller_permissions
    controller_permission = frappe.call(frappe.get_attr(method), doc=doc, ptype=ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.payment_entry_2
[ERROR] 2017-05-30 00:09:47,677 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-30 00:09:47.623031-47.30.120.59-fa1
[ERROR] 2017-05-30 00:10:49,080 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.form.load.getdoc", 
 "doctype": "Payment Entry", 
 "name": "PE-00001"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 35, in getdoc
    if not doc.has_permission("read"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 155, in has_permission
    return frappe.has_permission(self.doctype, permtype, self, verbose=verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 500, in has_permission
    out = frappe.permissions.has_permission(doctype, ptype, doc=doc, verbose=verbose, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 93, in has_permission
    controller_perm = has_controller_permissions(doc, ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 302, in has_controller_permissions
    controller_permission = frappe.call(frappe.get_attr(method), doc=doc, ptype=ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.payment_entry_2
[ERROR] 2017-05-30 00:10:49,088 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-30 00:10:49.081387-47.30.120.59-153
[ERROR] 2017-05-30 11:05:55,484 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.form.load.getdoc", 
 "doctype": "Payment Entry", 
 "name": "PE-00004"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 35, in getdoc
    if not doc.has_permission("read"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 155, in has_permission
    return frappe.has_permission(self.doctype, permtype, self, verbose=verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 500, in has_permission
    out = frappe.permissions.has_permission(doctype, ptype, doc=doc, verbose=verbose, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 93, in has_permission
    controller_perm = has_controller_permissions(doc, ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 302, in has_controller_permissions
    controller_permission = frappe.call(frappe.get_attr(method), doc=doc, ptype=ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.payment_entry_2
[ERROR] 2017-05-30 11:05:55,582 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-30 11:05:55.485647-122.160.159.227-aed
[ERROR] 2017-05-30 11:12:56,343 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.form.load.getdoc", 
 "doctype": "Payment Entry", 
 "name": "PE-00004"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 35, in getdoc
    if not doc.has_permission("read"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 155, in has_permission
    return frappe.has_permission(self.doctype, permtype, self, verbose=verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 500, in has_permission
    out = frappe.permissions.has_permission(doctype, ptype, doc=doc, verbose=verbose, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 93, in has_permission
    controller_perm = has_controller_permissions(doc, ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 302, in has_controller_permissions
    controller_permission = frappe.call(frappe.get_attr(method), doc=doc, ptype=ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.payment_entry_2
[ERROR] 2017-05-30 11:12:56,402 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-30 11:12:56.344032-122.160.159.227-1a9
[ERROR] 2017-05-30 11:13:16,987 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.form.load.getdoc", 
 "doctype": "Payment Entry", 
 "name": "PE-00004"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 35, in getdoc
    if not doc.has_permission("read"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 155, in has_permission
    return frappe.has_permission(self.doctype, permtype, self, verbose=verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 500, in has_permission
    out = frappe.permissions.has_permission(doctype, ptype, doc=doc, verbose=verbose, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 93, in has_permission
    controller_perm = has_controller_permissions(doc, ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 302, in has_controller_permissions
    controller_permission = frappe.call(frappe.get_attr(method), doc=doc, ptype=ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.payment_entry_2
[ERROR] 2017-05-30 11:13:16,995 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-30 11:13:16.989247-122.160.159.227-342
[ERROR] 2017-05-30 11:45:17,755 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.form.load.getdoc", 
 "doctype": "Payment Entry", 
 "name": "PE-00004"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 35, in getdoc
    if not doc.has_permission("read"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 155, in has_permission
    return frappe.has_permission(self.doctype, permtype, self, verbose=verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 500, in has_permission
    out = frappe.permissions.has_permission(doctype, ptype, doc=doc, verbose=verbose, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 93, in has_permission
    controller_perm = has_controller_permissions(doc, ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 302, in has_controller_permissions
    controller_permission = frappe.call(frappe.get_attr(method), doc=doc, ptype=ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.payment_entry_2
[ERROR] 2017-05-30 11:45:17,812 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-30 11:45:17.755895-122.160.159.227-f9f
[ERROR] 2017-05-30 11:54:32,085 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.form.load.getdoc", 
 "doctype": "Payment Entry", 
 "name": "PE-00004"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 35, in getdoc
    if not doc.has_permission("read"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 155, in has_permission
    return frappe.has_permission(self.doctype, permtype, self, verbose=verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 500, in has_permission
    out = frappe.permissions.has_permission(doctype, ptype, doc=doc, verbose=verbose, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 93, in has_permission
    controller_perm = has_controller_permissions(doc, ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 302, in has_controller_permissions
    controller_permission = frappe.call(frappe.get_attr(method), doc=doc, ptype=ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.payment_entry_2
[ERROR] 2017-05-30 11:54:32,090 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-30 11:54:32.085777-122.160.159.227-445
[ERROR] 2017-05-30 11:54:54,449 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.form.load.getdoc", 
 "doctype": "Payment Entry", 
 "name": "PE-00004"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 35, in getdoc
    if not doc.has_permission("read"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 155, in has_permission
    return frappe.has_permission(self.doctype, permtype, self, verbose=verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 500, in has_permission
    out = frappe.permissions.has_permission(doctype, ptype, doc=doc, verbose=verbose, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 93, in has_permission
    controller_perm = has_controller_permissions(doc, ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 302, in has_controller_permissions
    controller_permission = frappe.call(frappe.get_attr(method), doc=doc, ptype=ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.payment_entry_2
[ERROR] 2017-05-30 11:54:54,454 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-30 11:54:54.450089-122.160.159.227-281
[ERROR] 2017-05-30 11:54:58,099 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.form.load.getdoc", 
 "doctype": "Payment Entry", 
 "name": "90df935843"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 35, in getdoc
    if not doc.has_permission("read"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 155, in has_permission
    return frappe.has_permission(self.doctype, permtype, self, verbose=verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 500, in has_permission
    out = frappe.permissions.has_permission(doctype, ptype, doc=doc, verbose=verbose, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 93, in has_permission
    controller_perm = has_controller_permissions(doc, ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 302, in has_controller_permissions
    controller_permission = frappe.call(frappe.get_attr(method), doc=doc, ptype=ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.payment_entry_2
[ERROR] 2017-05-30 11:54:58,104 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-30 11:54:58.099830-122.160.159.227-f43
[ERROR] 2017-05-30 11:55:04,013 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.form.load.getdoc", 
 "doctype": "Payment Entry", 
 "name": "PE-00001"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 35, in getdoc
    if not doc.has_permission("read"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 155, in has_permission
    return frappe.has_permission(self.doctype, permtype, self, verbose=verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 500, in has_permission
    out = frappe.permissions.has_permission(doctype, ptype, doc=doc, verbose=verbose, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 93, in has_permission
    controller_perm = has_controller_permissions(doc, ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 302, in has_controller_permissions
    controller_permission = frappe.call(frappe.get_attr(method), doc=doc, ptype=ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.payment_entry_2
[ERROR] 2017-05-30 11:55:04,019 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-30 11:55:04.013772-122.160.159.227-2e9
[ERROR] 2017-05-30 11:56:37,794 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "action": "Save", 
 "cmd": "frappe.desk.form.save.savedocs", 
 "doc": "{\"docstatus\":0,\"doctype\":\"Payment Entry\",\"name\":\"New Payment Entry 2\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"protimr16@gmail.com\",\"naming_series\":\"PE-.#####\",\"payment_type\":\"Receive\",\"posting_date\":\"2017-05-30\",\"company\":\"MyPaperKart Pvt Ltd\",\"paid_from_account_currency\":\"INR\",\"paid_to_account_currency\":\"INR\",\"allocate_payment_amount\":1,\"account_payee\":\"Yes\",\"bearer\":\"Yes\",\"account_type\":\"Savings\",\"mode_of_payment\":\"Cheque\",\"paid_to\":\"IDFC Bank - MPL\",\"paid_to_account_balance\":12345,\"base_received_amount\":123456,\"unallocated_amount\":123456,\"difference_amount\":0,\"target_exchange_rate\":1,\"party_type\":\"Customer\",\"party\":\"Guest\",\"paid_from\":\"Debtors - MPL\",\"source_exchange_rate\":1,\"paid_from_account_balance\":0,\"party_balance\":0,\"references\":[],\"total_allocated_amount\":0,\"base_total_allocated_amount\":0,\"reference_no\":\"54456\",\"reference_date\":\"2017-05-31\",\"ifsc_code\":\"ABHY0070996\",\"city\":\"DEORIA\",\"branch\":\"DEORIA BRANCH\",\"micr\":\"274011002\",\"contact\":null,\"state\":\"UTTAR PRADESH\",\"bank_name\":\"ANDHRA BANK\",\"paid_amount\":123456,\"base_paid_amount\":123456,\"received_amount\":123456}"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 230, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 253, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 181, in insert
    self.check_permission("create")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 145, in check_permission
    if not self.has_permission(permtype):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 155, in has_permission
    return frappe.has_permission(self.doctype, permtype, self, verbose=verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 500, in has_permission
    out = frappe.permissions.has_permission(doctype, ptype, doc=doc, verbose=verbose, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 93, in has_permission
    controller_perm = has_controller_permissions(doc, ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 302, in has_controller_permissions
    controller_permission = frappe.call(frappe.get_attr(method), doc=doc, ptype=ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.payment_entry_2
[ERROR] 2017-05-30 11:56:37,803 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-30 11:56:37.795322-122.160.159.227-f6c
[ERROR] 2017-05-30 12:00:20,190 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.form.load.getdoc", 
 "doctype": "Payment Entry", 
 "name": "PE-00001"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 35, in getdoc
    if not doc.has_permission("read"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 155, in has_permission
    return frappe.has_permission(self.doctype, permtype, self, verbose=verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 500, in has_permission
    out = frappe.permissions.has_permission(doctype, ptype, doc=doc, verbose=verbose, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 93, in has_permission
    controller_perm = has_controller_permissions(doc, ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 302, in has_controller_permissions
    controller_permission = frappe.call(frappe.get_attr(method), doc=doc, ptype=ptype, user=user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 887, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.payment_entry_2
[ERROR] 2017-05-30 12:00:20,194 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-30 12:00:20.190551-122.160.159.227-f1c
[ERROR] 2017-05-30 12:00:32,684 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-30 12:00:32.680473-122.160.159.227-a2c
